import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';
import exec from 'k6/execution';

export const options = {
  stages: [
    { duration: '30s', target: 500 },
    { duration: '2m', target: 500 },
    { duration: '30s', target: 0 },
  ],
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const TOKEN = __ENV.API_KEY || 'test_benchmark_token';

const data = JSON.parse(open('./data.json'));
const apiKeys = data.api_keys || ['test_benchmark_token'];
const videoIds = data.video_ids || [];

export function setup() {
  const res = http.get(`${BASE_URL}/health`);
  if (res.status !== 200) {
    throw new Error(`API is not healthy, status: ${res.status}`);
  }
}

export default function () {
  const vuApiKey = apiKeys[exec.vu.idInTest % apiKeys.length];
  const params = {
    headers: {
      'Authorization': `Bearer ${vuApiKey}`,
      'Content-Type': 'application/json',
    },
  };

  const rand = Math.random();
  // 90% Reads, 10% Writes
  if (rand < 0.90) {
    // READ PATH
    const readRand = Math.random();
    if (readRand < 0.3) {
      const res = http.get(`${BASE_URL}/v1/videos`, params);
      check(res, { 'GET videos status 200': (r) => r.status === 200 });
    } else if (readRand < 0.6) {
      const vid = videoIds.length > 0 ? videoIds[exec.vu.idInTest % videoIds.length] : '123';
      const res = http.get(`${BASE_URL}/v1/videos/${vid}`, params);
      check(res, { 'GET video status 200 or 404': (r) => r.status === 200 || r.status === 404 });
    } else if (readRand < 0.8) {
      const res = http.get(`${BASE_URL}/v1/jobs`, params);
      check(res, { 'GET jobs status 200': (r) => r.status === 200 });
    } else {
      const res = http.get(`${BASE_URL}/v1/billing/subscription`, params);
      check(res, { 'GET billing subscription status 200': (r) => r.status === 200 });
    }
  } else {
    // WRITE PATH (10%)
    const payload = JSON.stringify({
      title: `Load Test Video ${exec.vu.idInTest}-${exec.scenario.iterationInTest}`,
      description: 'Generated by k6 production-mixed test'
    });
    const res = http.post(`${BASE_URL}/v1/videos`, payload, params);
    check(res, { 'POST video status 201': (r) => r.status === 201 });
  }
  
  sleep(1);
}
